import type { BoundaryRole } from '../types';

/**
 * Lookup table mapping package names to architectural boundary roles.
 * Covers npm, PyPI prefixes, and Go stdlib packages.
 * Used by the boundary role classifier to infer file roles from imports.
 */
export const boundaryRoleLookup: Map<string, BoundaryRole> = new Map<string, BoundaryRole>([
    // --- persistence ---
    ['pg', 'persistence'],
    ['pg-pool', 'persistence'],
    ['pg-native', 'persistence'],
    ['mysql', 'persistence'],
    ['mysql2', 'persistence'],
    ['mariadb', 'persistence'],
    ['mongoose', 'persistence'],
    ['mongodb', 'persistence'],
    ['typeorm', 'persistence'],
    ['prisma', 'persistence'],
    ['@prisma/client', 'persistence'],
    ['sequelize', 'persistence'],
    ['knex', 'persistence'],
    ['better-sqlite3', 'persistence'],
    ['sqlite3', 'persistence'],
    ['sql.js', 'persistence'],
    ['redis', 'persistence'],
    ['ioredis', 'persistence'],
    ['@redis/client', 'persistence'],
    ['cassandra-driver', 'persistence'],
    ['couchbase', 'persistence'],
    ['leveldb', 'persistence'],
    ['levelup', 'persistence'],
    ['lmdb', 'persistence'],
    ['drizzle-orm', 'persistence'],
    ['mikro-orm', 'persistence'],
    ['objection', 'persistence'],
    ['bookshelf', 'persistence'],
    ['waterline', 'persistence'],
    ['dynamoose', 'persistence'],
    ['@aws-sdk/client-dynamodb', 'persistence'],
    ['elasticsearch', 'persistence'],
    ['@elastic/elasticsearch', 'persistence'],
    ['neo4j-driver', 'persistence'],
    ['arangojs', 'persistence'],
    ['couchdb-nano', 'persistence'],
    ['nano', 'persistence'],
    ['rethinkdb', 'persistence'],
    // PyPI equivalents
    ['sqlalchemy', 'persistence'],
    ['psycopg2', 'persistence'],
    ['pymongo', 'persistence'],
    ['redis-py', 'persistence'],
    ['peewee', 'persistence'],
    // Go stdlib equivalents
    ['database/sql', 'persistence'],

    // --- http ---
    ['express', 'http'],
    ['fastify', 'http'],
    ['koa', 'http'],
    ['hapi', 'http'],
    ['@hapi/hapi', 'http'],
    ['restify', 'http'],
    ['polka', 'http'],
    ['micro', 'http'],
    ['feathers', 'http'],
    ['@feathersjs/feathers', 'http'],
    ['nestjs', 'http'],
    ['@nestjs/core', 'http'],
    ['@nestjs/common', 'http'],
    ['axios', 'http'],
    ['got', 'http'],
    ['node-fetch', 'http'],
    ['undici', 'http'],
    ['superagent', 'http'],
    ['needle', 'http'],
    ['request', 'http'],
    ['http', 'http'],
    ['https', 'http'],
    ['fetch', 'http'],
    ['cross-fetch', 'http'],
    ['ky', 'http'],
    ['wretch', 'http'],
    ['socket.io', 'http'],
    ['ws', 'http'],
    ['uws', 'http'],
    ['@fastify/cors', 'http'],
    ['cors', 'http'],
    ['helmet', 'http'],
    ['next', 'http'],
    ['nuxt', 'http'],
    ['remix', 'http'],
    ['sveltekit', 'http'],
    // PyPI
    ['flask', 'http'],
    ['django', 'http'],
    ['fastapi', 'http'],
    ['starlette', 'http'],
    ['aiohttp', 'http'],
    ['httpx', 'http'],
    ['requests', 'http'],
    ['tornado', 'http'],
    ['sanic', 'http'],
    // Go
    ['net/http', 'http'],
    ['github.com/gin-gonic/gin', 'http'],

    // --- messaging ---
    ['amqplib', 'messaging'],
    ['amqp', 'messaging'],
    ['kafkajs', 'messaging'],
    ['kafka-node', 'messaging'],
    ['@confluentinc/kafka-javascript', 'messaging'],
    ['rhea', 'messaging'],
    ['rhea-promise', 'messaging'],
    ['nats', 'messaging'],
    ['nats.ws', 'messaging'],
    ['node-nats-streaming', 'messaging'],
    ['@google-cloud/pubsub', 'messaging'],
    ['aws-sdk', 'messaging'],
    ['@aws-sdk/client-sqs', 'messaging'],
    ['@aws-sdk/client-sns', 'messaging'],
    ['azure-service-bus', 'messaging'],
    ['@azure/service-bus', 'messaging'],
    ['bull', 'messaging'],
    ['bullmq', 'messaging'],
    ['bee-queue', 'messaging'],
    ['agenda', 'messaging'],
    ['node-cron', 'messaging'],
    ['celery', 'messaging'],
    // PyPI
    ['pika', 'messaging'],
    ['confluent-kafka', 'messaging'],
    ['aiormq', 'messaging'],

    // --- auth ---
    ['jsonwebtoken', 'auth'],
    ['jwt-decode', 'auth'],
    ['passport', 'auth'],
    ['passport-jwt', 'auth'],
    ['passport-local', 'auth'],
    ['passport-google-oauth20', 'auth'],
    ['passport-github2', 'auth'],
    ['@auth/core', 'auth'],
    ['next-auth', 'auth'],
    ['clerk', 'auth'],
    ['@clerk/clerk-sdk-node', 'auth'],
    ['auth0', 'auth'],
    ['@auth0/auth0-react', 'auth'],
    ['@auth0/auth0-spa-js', 'auth'],
    ['keycloak-js', 'auth'],
    ['keycloak-connect', 'auth'],
    ['bcrypt', 'auth'],
    ['bcryptjs', 'auth'],
    ['argon2', 'auth'],
    ['crypto', 'auth'],
    ['oauth2-server', 'auth'],
    // PyPI
    ['pyjwt', 'auth'],
    ['python-jose', 'auth'],
    ['passlib', 'auth'],
    ['authlib', 'auth'],

    // --- validation ---
    ['zod', 'validation'],
    ['joi', 'validation'],
    ['yup', 'validation'],
    ['ajv', 'validation'],
    ['class-validator', 'validation'],
    ['validator', 'validation'],
    ['express-validator', 'validation'],
    ['superstruct', 'validation'],
    ['valibot', 'validation'],
    ['typebox', 'validation'],
    ['@sinclair/typebox', 'validation'],
    ['io-ts', 'validation'],
    ['runtypes', 'validation'],
    ['arktype', 'validation'],
    ['cerberus', 'validation'],
    // PyPI
    ['pydantic', 'validation'],
    ['marshmallow', 'validation'],
    ['wtforms', 'validation'],
    ['voluptuous', 'validation'],

    // --- observability ---
    ['@opentelemetry/api', 'observability'],
    ['@opentelemetry/sdk-node', 'observability'],
    ['@opentelemetry/auto-instrumentations-node', 'observability'],
    ['winston', 'observability'],
    ['pino', 'observability'],
    ['bunyan', 'observability'],
    ['morgan', 'observability'],
    ['debug', 'observability'],
    ['log4js', 'observability'],
    ['loglevel', 'observability'],
    ['consola', 'observability'],
    ['@sentry/node', 'observability'],
    ['@sentry/browser', 'observability'],
    ['dd-trace', 'observability'],
    ['newrelic', 'observability'],
    ['elastic-apm-node', 'observability'],
    ['prom-client', 'observability'],
    ['hot-shots', 'observability'],
    // PyPI
    ['structlog', 'observability'],
    ['loguru', 'observability'],
    ['sentry-sdk', 'observability'],
    ['opentelemetry-api', 'observability'],
    // Go
    ['log', 'observability'],
    ['go.uber.org/zap', 'observability'],

    // --- external-integration ---
    ['stripe', 'external-integration'],
    ['@stripe/stripe-js', 'external-integration'],
    ['twilio', 'external-integration'],
    ['sendgrid', 'external-integration'],
    ['@sendgrid/mail', 'external-integration'],
    ['nodemailer', 'external-integration'],
    ['mailchimp', 'external-integration'],
    ['@mailchimp/mailchimp_marketing', 'external-integration'],
    ['braintree', 'external-integration'],
    ['paypal', 'external-integration'],
    ['@paypal/checkout-server-sdk', 'external-integration'],
    ['plaid', 'external-integration'],
    ['@plaid/node', 'external-integration'],
    ['shopify-api', 'external-integration'],
    ['@shopify/shopify-api', 'external-integration'],
    ['github', 'external-integration'],
    ['@octokit/rest', 'external-integration'],
    ['@octokit/core', 'external-integration'],
    ['slack', 'external-integration'],
    ['@slack/web-api', 'external-integration'],
    ['@slack/bolt', 'external-integration'],
    ['discord.js', 'external-integration'],
    ['@google-cloud/storage', 'external-integration'],
    ['@aws-sdk/client-s3', 'external-integration'],
    ['@azure/storage-blob', 'external-integration'],
    ['firebase', 'external-integration'],
    ['firebase-admin', 'external-integration'],
    ['supabase-js', 'external-integration'],
    ['@supabase/supabase-js', 'external-integration'],
    ['algolia', 'external-integration'],
    ['algoliasearch', 'external-integration'],
    ['cloudinary', 'external-integration'],
    ['imagekit', 'external-integration'],
    // PyPI
    ['boto3', 'external-integration'],
    ['google-cloud-storage', 'external-integration'],
    ['mailjet', 'external-integration'],

    // --- VS Code extension and tooling ---
    ['vscode', 'external-integration'],
    ['@types/vscode', 'external-integration'],
    ['tree-sitter', 'external-integration'],
    ['web-tree-sitter', 'external-integration'],

    // --- MCP ---
    ['@modelcontextprotocol/sdk', 'http'],
]);
